from __future__ import annotations

import os
import unittest

from dotenv import load_dotenv

from src.common.db.connection import db_connection


load_dotenv()


CHATBOT_TABLES = (
    "qa_ticket",
    "ticket_analysis",
    "answer_draft",
    "evidence_docs",
    "safety_results",
    "final_response",
    "failed_queries",
    "voc_feedback",
    "payments",
    "refunds",
    "item_delivery_logs",
    "gacha_logs",
)

AUTO_ID_COLUMNS = {
    "ticket_analysis": "analysis_id",
    "answer_draft": "draft_id",
    "evidence_docs": "evidence_id",
    "safety_results": "safety_id",
    "final_response": "response_id",
    "failed_queries": "failed_query_id",
    "voc_feedback": "voc_id",
}


class TestChatbotDbSchema(unittest.TestCase):
    def setUp(self) -> None:
        if not os.environ.get("DB_PASSWORD"):
            self.skipTest("DB_PASSWORD environment variable is required")

    def _db_context_or_skip(self):
        db_context = db_connection()
        try:
            conn = db_context.__enter__()
        except Exception as exc:
            self.skipTest(f"Database connection is not available: {type(exc).__name__}")
        return db_context, conn

    def test_required_chatbot_tables_exist(self) -> None:
        db_context, conn = self._db_context_or_skip()
        try:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    SELECT table_name
                    FROM information_schema.tables
                    WHERE table_schema = 'public'
                      AND table_name = ANY(%s)
                    """,
                    (list(CHATBOT_TABLES),),
                )
                existing = {row[0] for row in cur.fetchall()}
        finally:
            db_context.__exit__(None, None, None)

        missing = sorted(set(CHATBOT_TABLES) - existing)
        self.assertEqual([], missing)

    def test_auto_id_columns_are_database_generated(self) -> None:
        db_context, conn = self._db_context_or_skip()
        try:
            with conn.cursor() as cur:
                for table_name, column_name in AUTO_ID_COLUMNS.items():
                    with self.subTest(table=table_name, column=column_name):
                        cur.execute(
                            """
                            SELECT column_default, is_identity
                            FROM information_schema.columns
                            WHERE table_schema = 'public'
                              AND table_name = %s
                              AND column_name = %s
                            """,
                            (table_name, column_name),
                        )
                        row = cur.fetchone()
                        self.assertIsNotNone(row, f"{table_name}.{column_name} does not exist")

                        column_default, is_identity = row
                        is_generated = bool(column_default) or is_identity == "YES"
                        self.assertTrue(
                            is_generated,
                            (
                                f"{table_name}.{column_name} must be generated by DB "
                                "(SERIAL, IDENTITY, or sequence default)."
                            ),
                        )
        finally:
            db_context.__exit__(None, None, None)


if __name__ == "__main__":
    unittest.main()
