-- Chatbot final response writes insight rows without supplying insight_id.
-- Ensure the primary key is generated by the database.

CREATE SEQUENCE IF NOT EXISTS insight_insight_id_seq OWNED BY insight.insight_id;

SELECT setval(
    'insight_insight_id_seq',
    COALESCE((SELECT MAX(insight_id) FROM insight), 0) + 1,
    false
);

ALTER TABLE insight
    ALTER COLUMN insight_id SET DEFAULT nextval('insight_insight_id_seq');
