"""Observability helpers shared across services."""

from common.observability.langsmith import configure_langsmith
from common.observability.logger import (
    EVENT_AGENT_DRAFTED,
    EVENT_DB_READ_COMPLETED,
    EVENT_DB_READ_FAILED,
    EVENT_DB_WRITE_COMPLETED,
    EVENT_DB_WRITE_FAILED,
    EVENT_FINAL_RESPONSE_CREATED,
    EVENT_NODE_COMPLETED,
    EVENT_NODE_STARTED,
    EVENT_NOTIFICATION_DISPATCHED,
    EVENT_NOTIFICATION_FAILED,
    EVENT_ORCHESTRATION_COMPLETED,
    EVENT_SAFETY_CHECKED,
    EVENT_TOOL_COMPLETED,
    EVENT_TOOL_STARTED,
    build_log_event,
    log_event,
)


__all__ = [
    "EVENT_AGENT_DRAFTED",
    "EVENT_DB_READ_COMPLETED",
    "EVENT_DB_READ_FAILED",
    "EVENT_DB_WRITE_COMPLETED",
    "EVENT_DB_WRITE_FAILED",
    "EVENT_FINAL_RESPONSE_CREATED",
    "EVENT_NODE_COMPLETED",
    "EVENT_NODE_STARTED",
    "EVENT_NOTIFICATION_DISPATCHED",
    "EVENT_NOTIFICATION_FAILED",
    "EVENT_ORCHESTRATION_COMPLETED",
    "EVENT_SAFETY_CHECKED",
    "EVENT_TOOL_COMPLETED",
    "EVENT_TOOL_STARTED",
    "build_log_event",
    "configure_langsmith",
    "log_event",
]
