"""Operation DB search agent.

This module handles DB-side evidence search for CS automation.
It supports two paths:
1. fixed_sql: predefined query templates by category/pattern
2. text_to_sql: structured LLM plan -> server-side SQL rendering

Final DB search output is normalized to one shape:
{
    "decision": {...},
    "query_type": "fixed_sql" | "text_to_sql",
    "plan": {...} | None,
    "sql": "...",
    "params": (...),
    "rows": [...],
    "evidence": [...],
}
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any, Literal

from psycopg.rows import dict_row
from pydantic import BaseModel, ConfigDict, Field
import yaml

from common.db.connection import db_connection
from common.llm.client import invoke_structured_llm


RoutingTarget = Literal["DB_only", "doc_only", "DB&DOC", "fixed_answer"]
Category = Literal["payment", "refund", "account", "bug", "gacha", "policy", "general"]
QueryType = Literal["fixed_sql", "text_to_sql"]

ALLOWED_SQL_ACTION_PREFIXES = ("select", "with")
DISALLOWED_SQL_PATTERNS = (
    r"\binsert\b",
    r"\bupdate\b",
    r"\bdelete\b",
    r"\bdrop\b",
    r"\balter\b",
    r"\btruncate\b",
    r"\bcreate\b",
    r"\bgrant\b",
    r"\brevoke\b",
    r"\bcopy\b",
    r";",
)

# backend 하위 tool 모듈 경로를 기준으로 프로젝트 루트의 data/sql을 바라보게 맞춘다.
SQL_ROOT = Path(os.environ.get("CS_AUTO_SQL_DIR", Path(__file__).resolve().parents[5] / "data" / "sql"))

QUERY_TYPE_DECISION_SYSTEM_PROMPT = """
You decide which DB retrieval strategy should be used for a customer-support
operation lookup.
Return JSON matching the schema exactly.
Choose "fixed_sql" when the request matches a stable predefined lookup pattern.
Choose "text_to_sql" when a dynamic structured query plan is needed.
Do not generate SQL.
""".strip()

TEXT_TO_SQL_SYSTEM_PROMPT = """
You generate only a database retrieval plan for customer-support operations.
Return JSON matching the schema exactly.
Never produce SQL directly.
Use only tables and columns explicitly listed in schema_context.
You may combine multiple tables when the question requires cross-checking
payments, refunds, account state, item delivery, gacha history, ticket state,
or admin events.
Treat category only as a retrieval hint, not as a hard restriction.
Prefer the minimum tables needed to answer the question, but join tables when
evidence from multiple sources is necessary.
Mark whether account_id or user_id scoping is required.
""".strip()


# ticket_analysis에서 DB 검색 경로에 필요한 필드만 추린 모델이다.
# 라우팅과 프롬프트 구성에서 공통으로 쓰는 분석 입력 스냅샷이다.
class RetrievalAnalysis(BaseModel):
    """Subset of ticket_analysis fields needed for DB retrieval."""

    model_config = ConfigDict(extra="ignore")

    analysis_id: int | None = None
    category: Category | str = "general"
    enriched_query: str | None = ""
    routing_target: RoutingTarget | str = "fixed_answer"
    summary: str | None = ""
    account_id: int | None = None
    user_id: int | None = None


# DB 조회 결과를 answer_agent가 바로 쓸 수 있는 근거 형태로 고정한다.
# source_type, source_id, evidence_text를 한 포맷으로 맞추기 위한 모델이다.
class EvidenceItem(BaseModel):
    """Normalized evidence row for downstream answer drafting."""

    model_config = ConfigDict(extra="ignore")

    source_type: str
    source_id: str | int | None = None
    evidence_text: str
    relevance_score: float = Field(default=1.0, ge=0.0, le=1.0)
    retrieval_rank: int = Field(default=1, ge=1)


# fixed_sql과 text_to_sql 중 어느 경로를 탈지 결정한 결과 모델이다.
# LLM 구조화 응답을 검증하고 이후 분기 로직에 그대로 넘기기 위해 쓴다.
class QueryTypeDecision(BaseModel):
    """Structured LLM decision for DB search mode."""

    query_type: QueryType
    reason: str = ""
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)


# text_to_sql 계획 안에서 WHERE 조건 1개를 표현하는 모델이다.
# 값이 티켓 필드에서 오는지 literal인지 구분해서 안전하게 바인딩한다.
class TextToSqlFilter(BaseModel):
    """Single WHERE clause unit in the generated plan."""

    column: str
    operator: Literal["=", "!=", ">", "<", ">=", "<=", "IN", "LIKE", "ILIKE"]
    value_source: Literal["literal", "ticket.account_id", "ticket.user_id", "ticket.ticket_id"]
    value: str | int | float | list[str] | list[int] | None = None


# text_to_sql 계획 안에서 테이블 간 조인 1개를 표현하는 모델이다.
# 허용된 조인 경로 안에서만 SQL을 조립하도록 구조를 고정한다.
class TextToSqlJoin(BaseModel):
    """Join edge between two allowlisted tables."""

    left: str
    right: str


# text_to_sql 계획 안에서 정렬 조건 1개를 표현하는 모델이다.
# LLM이 정렬 컬럼과 방향만 정하고 실제 SQL 문자열은 서버가 만든다.
class TextToSqlOrderBy(BaseModel):
    """ORDER BY clause unit."""

    column: str
    direction: Literal["asc", "desc"] = "desc"


# text_to_sql 경로에서 생성되는 구조화 조회 계획 전체 모델이다.
# 여러 테이블 조합, 필터, 조인, 정렬을 JSON 스키마 형태로 검증한다.
class TextToSqlPlan(BaseModel):
    """Structured text-to-sql plan generated by the LLM."""

    tables: list[str] = Field(default_factory=list)
    columns: list[str] = Field(default_factory=list)
    filters: list[TextToSqlFilter] = Field(default_factory=list)
    joins: list[TextToSqlJoin] = Field(default_factory=list)
    order_by: list[TextToSqlOrderBy] = Field(default_factory=list)
    limit: int = Field(default=20, ge=1, le=100)
    needs_account_scope: bool = True
    needs_user_scope: bool = False
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    reason: str = ""


# YAML에 분리한 고정 SQL 템플릿을 읽어오는 공통 로더다.
# SQL 원문을 코드와 분리해 관리하고 category별 템플릿을 재사용하게 한다.
def _load_sql_yaml(relative_path: str) -> dict[str, Any]:
    path = SQL_ROOT / relative_path
    raw_data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(raw_data, dict):
        raise ValueError(f"SQL YAML must be a mapping: {path}")
    return raw_data


FIXED_SQL_TEMPLATES = _load_sql_yaml("fixed_sql.yaml")


# 운영 DB의 허용 테이블, 컬럼, 조인 그래프를 한 번에 묶어 만드는 함수다.
# category는 제한이 아니라 preferred_tables 힌트로만 써서 다중 테이블 조합을 열어둔다.
def build_operation_schema_context(category: str) -> dict[str, object]:
    """Return the shared operation DB graph."""

    table_columns = {
        "game_accounts": [
            "account_id",
            "user_id",
            "game_name",
            "uid",
            "server_region",
            "account_status",
        ],
        "payments": [
            "payment_id",
            "account_id",
            "product_name",
            "product_type",
            "amount",
            "currency",
            "payment_method",
            "payment_status",
            "transaction_id",
            "paid_at",
        ],
        "refunds": [
            "refund_id",
            "payment_id",
            "refund_status",
            "refund_reason",
            "requested_at",
            "processed_at",
        ],
        "item_delivery_logs": [
            "delivery_id",
            "payment_id",
            "account_id",
            "source_type",
            "item_name",
            "quantity",
            "delivery_status",
            "expected_at",
            "delivered_at",
        ],
        "gacha_logs": [
            "gacha_id",
            "account_id",
            "banner_name",
            "item_name",
            "item_type",
            "rarity",
            "pity_count",
            "pulled_at",
        ],
        "qa_ticket": [
            "ticket_id",
            "account_id",
            "user_id",
            "title",
            "raw_query",
            "source_type",
            "status",
            "inquiry_created_at",
            "session_id",
            "responder_type",
        ],
        # admin_event_logs 테이블 사용 중단으로 스키마 컨텍스트에서 제외한다.
        # "admin_event_logs": [
        #     "log_id",
        #     "ticket_id",
        #     "session_id",
        #     "node_name",
        #     "event_type",
        #     "category",
        #     "routing_target",
        #     "tool_name",
        #     "status",
        #     "error_message",
        #     "error_category",
        #     "metadata",
        #     "created_at",
        # ],
    }
    preferred_tables_by_category = {
        "payment": ["payments", "refunds", "item_delivery_logs", "gacha_logs", "game_accounts"],
        "refund": ["refunds", "payments", "game_accounts", "item_delivery_logs"],
        # admin_event_logs 테이블 사용 중단으로 선호 테이블 목록에서 제외한다.
        "account": ["game_accounts", "qa_ticket"],
        "bug": ["qa_ticket", "game_accounts", "item_delivery_logs", "gacha_logs"],
        "gacha": ["gacha_logs", "item_delivery_logs", "payments", "game_accounts"],
        "policy": ["qa_ticket"],
        "general": ["qa_ticket", "game_accounts"],
    }
    return {
        "dialect": "postgres",
        "category_hint": category,
        "preferred_tables": preferred_tables_by_category.get(category, []),
        "allowed_tables": list(table_columns.keys()),
        "table_columns": table_columns,
        "join_paths": [
            ["game_accounts.account_id", "payments.account_id"],
            ["payments.payment_id", "refunds.payment_id"],
            ["game_accounts.account_id", "item_delivery_logs.account_id"],
            ["game_accounts.account_id", "gacha_logs.account_id"],
            ["qa_ticket.account_id", "game_accounts.account_id"],
            # admin_event_logs 테이블 사용 중단으로 관련 조인 경로는 제외한다.
            # ["qa_ticket.ticket_id", "admin_event_logs.ticket_id"],
            # ["qa_ticket.session_id", "admin_event_logs.session_id"],
            ["payments.account_id", "item_delivery_logs.account_id"],
        ],
        "required_scopes": ["ticket_id", "account_id"],
    }


# 경로 결정용 LLM 호출에 넣는 사용자 프롬프트를 조립하는 함수다.
# 문의 본문, 분석 결과, 스키마 힌트를 한 덩어리로 묶어 fixed/text 분기를 유도한다.
def _build_query_type_decision_user_prompt(
    question: str,
    analysis: dict[str, object],
    schema_context: dict[str, object],
) -> str:
    return (
        "Decide whether this operation DB lookup should use fixed_sql or text_to_sql.\n\n"
        f"question:\n{str(question or '').strip()[:2000]}\n\n"
        f"category: {str(analysis.get('category') or 'general')}\n"
        f"summary: {str(analysis.get('summary') or '').strip()[:1000]}\n"
        f"routing_target: {str(analysis.get('routing_target') or 'fixed_answer')}\n"
        f"enriched_query: {str(analysis.get('enriched_query') or '').strip()[:2000]}\n\n"
        f"schema_context:\n{schema_context}\n"
    )


# text_to_sql 계획 생성용 사용자 프롬프트를 조립하는 함수다.
# category 힌트와 스키마 그래프를 함께 넣어 여러 테이블 조합 계획을 유도한다.
def _build_text_to_sql_user_prompt(
    question: str,
    analysis: dict[str, object],
    schema_context: dict[str, object],
) -> str:
    return (
        "Build a DB retrieval plan for this customer-support inquiry.\n\n"
        f"question:\n{str(question or '').strip()[:2000]}\n\n"
        f"category: {str(analysis.get('category') or 'general')}\n"
        f"summary: {str(analysis.get('summary') or '').strip()[:1000]}\n"
        f"routing_target: {str(analysis.get('routing_target') or 'fixed_answer')}\n"
        f"enriched_query: {str(analysis.get('enriched_query') or '').strip()[:2000]}\n\n"
        f"schema_context:\n{schema_context}\n"
    )


# fixed_sql과 text_to_sql 중 어느 경로를 탈지 LLM으로 먼저 판단하는 함수다.
# 이후 실제 검색 클래스를 선택하는 라우팅 단계의 단일 진입점으로 쓴다.
def decide_query_type(
    question: str,
    analysis: dict[str, object],
    schema_context: dict[str, object],
) -> QueryTypeDecision:
    """Decide fixed_sql vs text_to_sql using structured LLM output."""

    return invoke_structured_llm(
        system_prompt=QUERY_TYPE_DECISION_SYSTEM_PROMPT,
        user_prompt=_build_query_type_decision_user_prompt(question, analysis, schema_context),
        response_model=QueryTypeDecision,
    )


# text_to_sql 경로에서만 쓰는 구조화 조회 계획 생성 함수다.
# SQL 문자열을 직접 만들지 않고 계획 객체만 받아 서버가 후속 렌더링을 맡는다.
def build_text_to_sql_plan(
    question: str,
    analysis: dict[str, object],
    schema_context: dict[str, object],
) -> TextToSqlPlan:
    """Build a structured text-to-sql plan."""

    return invoke_structured_llm(
        system_prompt=TEXT_TO_SQL_SYSTEM_PROMPT,
        user_prompt=_build_text_to_sql_user_prompt(question, analysis, schema_context),
        response_model=TextToSqlPlan,
    )


# 계획에 들어 있는 필터 값을 실제 티켓 데이터로 해석하는 함수다.
# ticket.account_id 같은 참조를 안전하게 파라미터 값으로 치환한다.
def _resolve_filter_value(raw_filter: TextToSqlFilter, ticket: dict[str, object]) -> object:
    if raw_filter.value_source == "literal":
        return raw_filter.value
    if raw_filter.value_source == "ticket.account_id":
        return ticket.get("account_id")
    if raw_filter.value_source == "ticket.user_id":
        return ticket.get("user_id")
    if raw_filter.value_source == "ticket.ticket_id":
        return ticket.get("ticket_id")
    return None


# YAML fixed_sql에 적힌 파라미터 정의를 실제 실행 값으로 바꾸는 함수다.
# ticket.xxx 참조와 literal 값을 같은 방식으로 처리하기 위해 분리했다.
def _resolve_fixed_sql_param(raw_value: object, ticket: dict[str, object]) -> object:
    if isinstance(raw_value, str) and raw_value.startswith("ticket."):
        return ticket.get(raw_value.removeprefix("ticket."))
    return raw_value


# category별 fixed_sql 템플릿 매핑을 조회하는 함수다.
# YAML 구조가 깨졌을 때 초기에 실패하게 해서 잘못된 SQL 실행을 막는다.
def _fixed_sql_template_for_category(category: str) -> dict[str, object]:
    template = FIXED_SQL_TEMPLATES.get(category) or {}
    if not isinstance(template, dict):
        raise ValueError(f"Fixed SQL template must be a mapping: {category}")
    return template


# fixed_sql 경로에서 YAML 템플릿과 파라미터를 합쳐 실행 SQL을 만드는 함수다.
# 쿼리 원문은 파일에서 관리하고 코드에서는 값 바인딩만 담당하게 분리했다.
def render_fixed_sql(
    category: str,
    ticket: dict[str, object],
) -> tuple[str, tuple[object, ...], str]:
    template = _fixed_sql_template_for_category(category)
    sql = str(template.get("sql") or "").strip()
    raw_params = template.get("params") or []
    source_type = str(template.get("source_type") or "operation_db_fixed")
    if not sql or not isinstance(raw_params, list):
        return "", (), source_type
    params = tuple(_resolve_fixed_sql_param(raw_value, ticket) for raw_value in raw_params)
    return sql, params, source_type


# text_to_sql 계획 객체를 실제 파라미터 바인딩 SQL로 바꾸는 함수다.
# 모델은 구조만 정하고 SQL 문자열 조립은 서버 코드가 맡도록 하는 안전 장치다.
def _table_name_from_ref(ref: str) -> str:
    return str(ref or "").split(".", 1)[0]


def _join_condition_for_tables(
    left_table: str,
    right_table: str,
    schema_context: dict[str, object] | None,
) -> tuple[str, str] | None:
    if not schema_context:
        return None
    join_paths = schema_context.get("join_paths") or []
    for path in join_paths:
        if not isinstance(path, list) or len(path) != 2:
            continue
        left_ref = str(path[0])
        right_ref = str(path[1])
        left_ref_table = _table_name_from_ref(left_ref)
        right_ref_table = _table_name_from_ref(right_ref)
        if left_ref_table == left_table and right_ref_table == right_table:
            return left_ref, right_ref
        if left_ref_table == right_table and right_ref_table == left_table:
            return right_ref, left_ref
    return None


def render_text_to_sql(
    plan: TextToSqlPlan,
    ticket: dict[str, object],
    schema_context: dict[str, object] | None = None,
) -> tuple[str, tuple[object, ...]]:
    if not plan.tables:
        return "", ()

    base_table = plan.tables[0]
    columns = ", ".join(plan.columns) if plan.columns else "*"
    sql_parts = [f"SELECT {columns}", f"FROM {base_table}"]
    params: list[object] = []
    joined_tables: set[str] = {base_table}

    for join in plan.joins:
        right_table = _table_name_from_ref(join.right)
        if right_table in joined_tables:
            continue
        sql_parts.append(f"JOIN {right_table} ON {join.left} = {join.right}")
        joined_tables.add(right_table)

    referenced_tables = {base_table}
    referenced_tables.update(_table_name_from_ref(column) for column in plan.columns if "." in column)
    for raw_filter in plan.filters:
        referenced_tables.add(_table_name_from_ref(raw_filter.column))
    referenced_tables.update(str(table) for table in plan.tables[1:])

    for target_table in sorted(referenced_tables):
        if target_table in joined_tables:
            continue
        join_condition = _join_condition_for_tables(base_table, target_table, schema_context)
        if join_condition is None:
            for joined_table in sorted(joined_tables):
                join_condition = _join_condition_for_tables(joined_table, target_table, schema_context)
                if join_condition is not None:
                    break
        if join_condition is None:
            continue
        left_ref, right_ref = join_condition
        sql_parts.append(f"JOIN {target_table} ON {left_ref} = {right_ref}")
        joined_tables.add(target_table)

    where_clauses: list[str] = []
    for raw_filter in plan.filters:
        value = _resolve_filter_value(raw_filter, ticket)
        if raw_filter.operator == "IN" and isinstance(value, list) and value:
            placeholders = ", ".join(["%s"] * len(value))
            where_clauses.append(f"{raw_filter.column} IN ({placeholders})")
            params.extend(value)
            continue
        where_clauses.append(f"{raw_filter.column} {raw_filter.operator} %s")
        params.append(value)

    if where_clauses:
        sql_parts.append("WHERE " + " AND ".join(where_clauses))

    if plan.order_by:
        order_clause = ", ".join(f"{item.column} {item.direction.upper()}" for item in plan.order_by)
        sql_parts.append(f"ORDER BY {order_clause}")

    sql_parts.append("LIMIT %s")
    params.append(plan.limit)
    return " ".join(sql_parts), tuple(params)


# 렌더링된 SQL이 허용 범위 안에 있는지 실행 전에 검증하는 함수다.
# SELECT/CTE만 허용하고 allowlist 밖 테이블이나 위험 구문을 차단한다.
def validate_sql_query(
    sql: str,
    params: tuple[object, ...],
    schema_context: dict[str, object],
) -> None:
    normalized = sql.strip().lower()
    if not normalized:
        raise ValueError("SQL is empty")
    if not normalized.startswith(ALLOWED_SQL_ACTION_PREFIXES):
        raise ValueError("Only SELECT/CTE queries are allowed")

    for pattern in DISALLOWED_SQL_PATTERNS:
        if re.search(pattern, normalized, flags=re.IGNORECASE):
            raise ValueError(f"Disallowed SQL pattern detected: {pattern}")

    allowlisted_tables = {str(table).lower() for table in schema_context.get("allowed_tables", [])}
    for candidate in re.findall(r"\bfrom\s+([a-zA-Z_][\w]*)|\bjoin\s+([a-zA-Z_][\w]*)", normalized):
        table_name = next((item for item in candidate if item), "")
        if table_name and table_name not in allowlisted_tables:
            raise ValueError(f"Table is not allowlisted: {table_name}")

    if any(param is None for param in params):
        raise ValueError("SQL parameters contain None")


# DB 원본 row 리스트를 answer_agent용 evidence 포맷으로 바꾸는 함수다.
# source_id와 evidence_text를 통일해서 상위 단계가 같은 방식으로 소비하게 만든다.
def _rows_to_evidence(
    rows: list[dict[str, object]],
    source_type: str,
) -> list[dict[str, object]]:
    evidence: list[dict[str, object]] = []
    for index, row in enumerate(rows, start=1):
        evidence.append(
            EvidenceItem(
                source_type=source_type,
                source_id=str(
                    row.get("id")
                    or row.get("payment_id")
                    or row.get("refund_id")
                    or row.get("delivery_id")
                    or row.get("gacha_id")
                    or row.get("account_id")
                    or row.get("ticket_id")
                    or index
                ),
                evidence_text=str(row),
                relevance_score=max(0.0, 1.0 - ((index - 1) * 0.1)),
                retrieval_rank=index,
            ).model_dump()
        )
    return evidence


# 실제 DB 커넥션을 열고 SQL을 실행하는 공통 실행 함수다.
# fixed_sql과 text_to_sql 경로가 같은 실행기와 fetch 포맷을 재사용하게 한다.
def _execute_sql(
    sql: str,
    params: tuple[object, ...],
) -> list[dict[str, object]]:
    with db_connection() as conn:
        with conn.cursor(row_factory=dict_row) as cur:
            cur.execute(sql, params)
            return [dict(row) for row in cur.fetchall()]


# YAML에 정의된 고정 SQL 경로만 전담하는 검색 클래스다.
# 자주 쓰는 패턴 조회를 빠르게 실행하고 결과를 evidence 포맷으로 돌려준다.
class FixedSqlSearcher:
    """Encapsulate YAML-managed fixed SQL lookup flow."""

    def run(self, ticket: dict[str, object], analysis: dict[str, object]) -> dict[str, object]:
        category = str(analysis.get("category") or "general").lower()
        schema_context = build_operation_schema_context(category)
        sql, params, source_type = render_fixed_sql(category, ticket)

        if not sql:
            return {
                "decision": None,
                "query_type": "fixed_sql",
                "plan": None,
                "sql": "",
                "params": (),
                "rows": [],
                "evidence": [],
            }

        validate_sql_query(sql, params, schema_context)
        rows = _execute_sql(sql, params)
        return {
            "decision": None,
            "query_type": "fixed_sql",
            "plan": None,
            "sql": sql,
            "params": params,
            "rows": rows,
            "evidence": _rows_to_evidence(rows, source_type),
        }


# LLM 계획 생성부터 SQL 렌더링, 검증, 실행까지 맡는 text_to_sql 클래스다.
# category를 힌트로만 사용하면서 여러 테이블 조합 조회를 수행하는 경로다.
class TextToSqlSearcher:
    """Encapsulate structured text-to-sql planning and execution flow."""

    def build_schema_context(self, category: str) -> dict[str, object]:
        return build_operation_schema_context(category)

    def build_plan(self, question: str, analysis: dict[str, object], schema_context: dict[str, object]) -> TextToSqlPlan:
        return build_text_to_sql_plan(question, analysis, schema_context)

    def run(self, ticket: dict[str, object], analysis: dict[str, object]) -> dict[str, object]:
        category = str(analysis.get("category") or "general").lower()
        question = str(analysis.get("enriched_query") or ticket.get("raw_query") or ticket.get("title") or "")
        schema_context = self.build_schema_context(category)
        plan = self.build_plan(question, analysis, schema_context)
        sql, params = render_text_to_sql(plan, ticket, schema_context)

        if not sql:
            return {
                "decision": None,
                "query_type": "text_to_sql",
                "plan": plan.model_dump(),
                "sql": "",
                "params": (),
                "rows": [],
                "evidence": [],
            }

        try:
            validate_sql_query(sql, params, schema_context)
            rows = _execute_sql(sql, params)
        except Exception as exc:  # pragma: no cover - live DB plan failures are dataset noise, not code paths.
            return {
                "decision": {
                    "query_type": "text_to_sql",
                    "reason": f"text_to_sql execution failed: {type(exc).__name__}",
                    "confidence": plan.confidence,
                },
                "query_type": "text_to_sql",
                "plan": plan.model_dump(),
                "sql": sql,
                "params": params,
                "rows": [],
                "evidence": [],
                "error": f"{type(exc).__name__}: {exc}",
            }
        return {
            "decision": None,
            "query_type": "text_to_sql",
            "plan": plan.model_dump(),
            "sql": sql,
            "params": params,
            "rows": rows,
            "evidence": _rows_to_evidence(rows, "operation_db_text_to_sql"),
        }


# fixed_sql과 text_to_sql 클래스 사이를 분기하는 상위 라우터 클래스다.
# query_type 결정 결과를 기준으로 실제 검색 구현체 하나를 선택해 실행한다.
class DbSearchRouter:
    """Route DB search between fixed_sql and text_to_sql implementations."""

    def __init__(self) -> None:
        self.fixed_sql = FixedSqlSearcher()
        self.text_to_sql = TextToSqlSearcher()

    def decide_query_type(self, ticket: dict[str, object], analysis: dict[str, object]) -> QueryTypeDecision:
        category = str(analysis.get("category") or "general").lower()
        question = str(analysis.get("enriched_query") or ticket.get("raw_query") or ticket.get("title") or "")
        schema_context = self.text_to_sql.build_schema_context(category)
        return decide_query_type(question, analysis, schema_context)

    def run(self, ticket: dict[str, object], analysis: dict[str, object]) -> dict[str, object]:
        decision = self.decide_query_type(ticket, analysis)
        if decision.query_type == "fixed_sql":
            result = self.fixed_sql.run(ticket, analysis)
        else:
            result = self.text_to_sql.run(ticket, analysis)

        return {
            "decision": decision.model_dump(),
            "query_type": result["query_type"],
            "plan": result["plan"],
            "sql": result["sql"],
            "params": result["params"],
            "rows": result["rows"],
            "evidence": result["evidence"],
        }
