from __future__ import annotations

MAX_SAFETY_RETRY = 2
MAX_MASKING_RETRY = 2
ROUTING_TARGET = ["rag_reply", "urgent_alert"]
CATEGORY = ["결제", "인게임버그", "FAQ", "VOC"]
FACTUALITY_THRESHOLD = 0.8
HALLUCINATION_THRESHOLD = 0.3
FACTUALITY_WARN_THRESHOLD = 0.5
HALLUCINATION_WARN_THRESHOLD = 0.5
FACTUALITY_BLOCK_THRESHOLD = 0.3
HALLUCINATION_BLOCK_THRESHOLD = 0.7
TOXICITY_THRESHOLD = 0.7
VOC_FIXED_RESPONSE = "지금은 이해할 수 없는 내용이에요.\n홈페이지 참고하시거나 추후 안내드리겠습니다."
